### ISSUE TITLE
Set Color from Activity

### ISSUE THREAD

**Issue by maxcriser** [maxcriser/EpamTrainingProject#13]
1.

int color = Integer.parseInt("bdbdbd", 16)+0xFF000000);
textview.setTextColor(color);
2.

textView.setTextColor(getResources().getColor(R.color.some_color));
3.

textView.setTextColor(0xffbdbdbd);
4.

textView.setTextColor(Color.parseColor("#bdbdbd"));
5.

textView.setTextColor(Color.argb(a_int, r_int, g_int, b_int));

**Comment by maxcriser** [comment]
~~getColor~~ is deprecated

**Comment by anandwana** [comment]
Make a Holder -   Holder holder=new Holder();
Get the View,
 @Override
    public View getView(final int position, View convertView, ViewGroup parent) {}
holder.tv=(TextView) rowView.findViewById(your id);
  holder.tv.setBackgroundColor(Color.rgb(237, 85 , 100));
