### ISSUE TITLE
How to don't copy all layout at productFlavors

### ISSUE THREAD

**Issue by maxcriser** [maxcriser/EpamTrainingProject#15]
How to don't copy all layout at productFlavors
for example maybe <include layout....> from other flavor

**Comment by alexdzeshko** [comment]
Question isn't clear for me. Please rephrase or ask at class.

**Comment by maxcriser** [comment]
Sorry, it's just my notes with whom I need to figure out yourself ))). Only I can understand it ))) if I have any questions I will ask in issue to rep "epam-training-2016" or at class )
