### ISSUE TITLE
How to organize the save settings

### ISSUE THREAD

**Issue by maxcriser** [maxcriser/EpamTrainingProject#16]
Addiction sparcearray from first activity to second anctivity, read types language and recources from database or static?

**Comment by alexdzeshko** [comment]
Question isn't clear for me. Please rephrase or ask at class.

**Comment by maxcriser** [comment]
Sorry, it's just my notes with whom I need to figure out yourself ))). Only I can understand it ))) if I have any questions I will ask in issue to rep "epam-training-2016" or at class )
