### ISSUE TITLE
Determine the prevailing tone in the picture

### ISSUE THREAD

**Issue by maxcriser** [maxcriser/EpamTrainingProject#23]
How to determine the prevailing tone in the picture Android

**Comment by alexdzeshko** [comment]
Use Palette from support library

**Comment by alexdzeshko** [comment]
also see https://github.com/nickbutcher/plaid/blob/master/app/src/main/java/io/plaidapp/util/ColorUtils.java#L111

**Comment by maxcriser** [comment]
Thank you!
