### ISSUE TITLE
Fonts

### ISSUE THREAD

**Issue by maxcriser** [maxcriser/EpamTrainingProject#7]
How to create font for textview/button/etc

**Comment by anandwana** [comment]
Use Typeface.
This is for custom fonts.
Typeface custom_font = Typeface.createFromAsset(getAssets(), "yourFontName.ttf");
yourText.setTypeface(custom_font);

**Comment by maxcriser** [comment]
For ItemView&item: http://stackoverflow.com/questions/27588965/how-to-use-custom-font-in-android-studio
